#include <Arduino.h>
#include <lvgl.h>
#include <TFT_eSPI.h>
#include <Wire.h>
#include <RTClib.h>
#include "vars.h"
#include "eez-flow.h"
// ---------- IMPORTANT ----------
// DO NOT wrap EEZ headers with extern "C".
// EEZ generated headers use C++ features (templates, namespaces).
// Include them normally:
#include "ui.h"        // generated by EEZ Studio (ui.c / ui.h must be in project)
#include "screens.h"

RTC_PCF8563 rtc;


// Calibration constants
const uint16_t RAW_MIN_X = 429;
const uint16_t RAW_MAX_X = 3593;
const uint16_t RAW_MIN_Y = 1905;
const uint16_t RAW_MAX_Y = 3345;

const bool SWAP_AXES = false;
const bool INVERT_X  = true;
const bool INVERT_Y  = false;

// ---------------- Display ----------------
TFT_eSPI tft = TFT_eSPI();
HardwareSerial LoRa(1);
static lv_disp_draw_buf_t draw_buf;
static lv_color_t buf1[320 * 40];

//LORA CODES
int last_rssi = -1;
int my_address = 2;
int target_address = 3;  // default
int my_network_id = 6;
String last_sent_message = "";
String target_name = "Arul";   // default
int packet_counter = 0;


const char* names[] = {
    "Legend",
    "Kartis",
    "Kiran",
    "Arul",
    "Renga",
    "Stellas",
    "Sharath",
    "Derick"
};

String get_name_from_address(int addr){
    if(addr >= 1 && addr <= 8){
        return String(names[addr - 1]);
    }
    return String("Unknown");
}

void loraAT(String cmd){
    while(LoRa.available()) LoRa.read();
    LoRa.print(cmd + "\r\n");  // not println
    delay(600);
    String r = "";
    while(LoRa.available()) r += (char)LoRa.read();
    r.trim();
    Serial.println(cmd + " => " + (r.length() ? r : "NO RESPONSE"));
}

void sync_network_ui(){
    char buf[16];

    sprintf(buf,"%d", my_address);
    lv_label_set_text(objects.net_add_variable_1, buf);
    lv_label_set_text(objects.net_add_variable, buf);

    sprintf(buf,"%d", my_network_id);
    lv_label_set_text(objects.net_id_variable_1, buf);
    lv_label_set_text(objects.net_id_variable, buf);

    lv_dropdown_set_selected(objects.net_address_selector, my_address - 1);
    lv_dropdown_set_selected(objects.net_id_selector, my_network_id - 1);
    lv_dropdown_set_selected(objects.target_net_address_selector, target_address - 1);
    lv_dropdown_set_selected(objects.target_name_selector, target_address - 1);
}
void update_target_display(){
    char buf[16];
    sprintf(buf,"%d", target_address);

    lv_label_set_text(objects.packets_variable_label_2, buf);
    lv_label_set_text(objects.packets_variable_label_3, buf);
}


void update_packet_counter(){
    char buf[16];
    sprintf(buf,"%d",packet_counter);

    lv_label_set_text(objects.packets_variable_label, buf);
    lv_label_set_text(objects.packets_variable_label_1, buf);
}

void process_lora_message(String msg, int rssi, int sender){
    char timebuf[6];
    get_time_string(timebuf);
    maintain_chat_limit();
    
    char line[128];
    String display_name = get_name_from_address(sender);
    sprintf(line, "\n\n[%s] %s: %s", timebuf, display_name.c_str(), msg.c_str());


    lv_textarea_add_text(objects.chatting_area_box, line);

    lv_obj_scroll_to_y(objects.chatting_area_box, LV_COORD_MAX, LV_ANIM_OFF);
}


static inline int32_t fmap_clamped(int32_t val, int32_t in_min, int32_t in_max,
                                   int32_t out_min, int32_t out_max) {
    if (in_max == in_min) return out_min;

    long mapped = (long)(val - in_min) * (out_max - out_min) /
                  (long)(in_max - in_min) + out_min;

    if (mapped < out_min) return out_min;
    if (mapped > out_max) return out_max;
    return (int32_t)mapped;
}

// ---------------- Flush ----------------
void my_disp_flush(lv_disp_drv_t *disp,
                   const lv_area_t *area,
                   lv_color_t *color_p){
  uint32_t w = (uint32_t)(area->x2 - area->x1 + 1);
  uint32_t h = (uint32_t)(area->y2 - area->y1 + 1);

  tft.startWrite();
  tft.setAddrWindow(area->x1, area->y1, w, h);
  tft.pushColors((uint16_t *)color_p, w * h, false);
  tft.endWrite();

  lv_disp_flush_ready(disp);
}

void my_touch_read(lv_indev_drv_t *indev, lv_indev_data_t *data) {
    uint16_t tx = 0, ty = 0;
    bool pressed = tft.getTouch(&tx, &ty);

    const uint16_t sw = tft.width();   // 320
    const uint16_t sh = tft.height();  // 240

    if (!pressed) {
        data->state = LV_INDEV_STATE_REL;
        return;
    }

    data->state = LV_INDEV_STATE_PR;

    bool scaled = (tx <= sw && ty <= sh);

    int32_t mx, my;

    if (scaled) {
        mx = SWAP_AXES ? ty : tx;
        my = SWAP_AXES ? tx : ty;
    } else {
        if (SWAP_AXES) {
            mx = fmap_clamped(ty, RAW_MIN_Y, RAW_MAX_Y, 0, sw);
            my = fmap_clamped(tx, RAW_MIN_X, RAW_MAX_X, 0, sh);
        } else {
            mx = fmap_clamped(tx, RAW_MIN_X, RAW_MAX_X, 0, sw);
            my = fmap_clamped(ty, RAW_MIN_Y, RAW_MAX_Y, 0, sh);
        }
    }

    if (INVERT_X) mx = sw - mx;
    if (INVERT_Y) my = sh - my;

    if (mx < 0) mx = 0;
    if (mx > sw) mx = sw;
    if (my < 0) my = 0;
    if (my > sh) my = sh;

    data->point.x = (lv_coord_t)mx;
    data->point.y = (lv_coord_t)my;

    //Serial.printf("TOUCH RAW: %u %u | MAPPED: %ld %ld\n", tx, ty, mx, my);
}

void get_time_string(char *buf){
    DateTime now = rtc.now();
    sprintf(buf,"%02d:%02d", now.hour(), now.minute());
}

void btn_send_cb(lv_event_t * e) {
    // When the button is pressed, call your custom function!
    send_display_message(); 
}

void save_lora_settings_cb(lv_event_t * e) {
    my_address     = lv_dropdown_get_selected(objects.net_address_selector) + 1;
    my_network_id  = lv_dropdown_get_selected(objects.net_id_selector) + 1;  // UI only
    target_address = lv_dropdown_get_selected(objects.target_net_address_selector) + 1;

    char name_buf[32];
    lv_dropdown_get_selected_str(objects.target_name_selector, name_buf, sizeof(name_buf));
    target_name = String(name_buf);

    Serial.printf("Saved: MY=%d NET=%d(UI only) TARGET=%d NAME=%s\n",
                  my_address, my_network_id, target_address, target_name.c_str());

    // Only send ADDRESS to module — NETWORKID not supported in proprietary mode
    LoRa.printf("AT+ADDRESS=%d\r\n", my_address);
    delay(300);

    sync_network_ui();
    update_target_display();
}

void resend_last_message(lv_event_t * e){

    if(last_sent_message.length() == 0) return;

    char timebuf[6];
    get_time_string(timebuf);

    LoRa.printf("AT+SEND=%d,%d,%s\r\n",
                target_address,
                last_sent_message.length(),
                last_sent_message.c_str());

    packet_counter++;
    update_packet_counter();

    char line[128];
    sprintf(line, "\n\n[%s] ME (RESEND): %s",
            timebuf,
            last_sent_message.c_str());

    lv_textarea_add_text(objects.chatting_area_box, line);
}


// ---------------- Setup ----------------
void setup(){
  Serial.begin(115200);
  delay(100);
    // RYLR998 UART — add this before AT commands
  LoRa.begin(9600, SERIAL_8N1, 14, 13);  // RX=13, TX=14
  delay(300);

    Serial.println("=== LORA INIT ===");
    loraAT("AT");
    loraAT("AT+BAND=865000000");
    loraAT("AT+PARAMETER=12,7,1,12");
    loraAT("AT+CRFOP=14");                 // TX power 14dBm
    loraAT("AT+ADDRESS=" + String(my_address));

    Serial.println("=== VERIFY ===");
    loraAT("AT+BAND?");
    loraAT("AT+PARAMETER?");
    loraAT("AT+ADDRESS?");
    Serial.println("=== LORA DONE ===");

    delay(200);
    while(LoRa.available()){
    Serial.write(LoRa.read());  // should print "+OK" in Serial Monitor
    }
    delay(100);

    Wire.begin(25, 26);   // your RTC pins

    if (!rtc.begin()) {
        Serial.println("RTC not found");
    }

    tft.begin();
    tft.setRotation(3);

    tft.initDMA();

  lv_init();


  // Display driver
  lv_disp_draw_buf_init(&draw_buf, buf1, NULL, 320 * 40);

  static lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.draw_buf = &draw_buf;
  disp_drv.hor_res = 320;
  disp_drv.ver_res = 240;
  lv_disp_drv_register(&disp_drv);

  // Touch driver (pointer)
  static lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = my_touch_read;
  lv_indev_drv_register(&indev_drv);

  // ----- EEZ: initialize UI + Flow (ui_init is generated by EEZ) -----
  // Make sure ui.c/.cpp and the rest of the EEZ-generated files are present in the sketch.
  ui_init();
lv_scr_load(objects.main);

  sync_network_ui();
    LoRa.printf("AT+ADDRESS=%d\r\n", my_address);
    delay(300);



  Serial.println("ui_init() done");
  // This directly links the button to your function, bypassing EEZ Flow entirely!
    lv_obj_add_event_cb(objects.send_button, btn_send_cb, LV_EVENT_CLICKED, NULL);
    
    // (Optional) If you also want the keyboard's "Enter/Checkmark" key to send messages:
    lv_obj_add_event_cb(objects.keyboard_1, btn_send_cb, LV_EVENT_READY, NULL);
    lv_obj_add_event_cb(objects.save_button, save_lora_settings_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(objects.resend_button, resend_last_message, LV_EVENT_CLICKED, NULL);

    

update_packet_counter();
update_target_display();
}

void add_chat_message(const char *prefix, const char *msg){
    lv_textarea_add_text(objects.chatting_area_box, prefix);
    lv_textarea_add_text(objects.chatting_area_box, msg);
    lv_textarea_add_text(objects.chatting_area_box, "\n");

    // auto scroll to bottom
    lv_obj_scroll_to_y(objects.chatting_area_box, LV_COORD_MAX, LV_ANIM_OFF);
}


void send_display_message(){
    // 1. Get the typed message from the keyboard text area
    const char *msg = lv_textarea_get_text(objects.textarea_1);
    
    // If empty, do nothing
    if(strlen(msg) == 0) return;
    

    // Get the real time from RTC
    char timebuf[6];    
    get_time_string(timebuf);
    maintain_chat_limit();

    // actually transmit over LoRa
    LoRa.printf("AT+SEND=%d,%d,%s\r\n", target_address, strlen(msg), msg);
    packet_counter++;
    update_packet_counter();
    last_sent_message = String(msg);   // 🔥 STORE LAST MESSAGE

    char line[128];
    sprintf(line, "\n\n[%s] ME: %s", timebuf, msg);
    lv_textarea_add_text(objects.chatting_area_box, line);

    // 4. Auto-scroll to the bottom
    lv_obj_scroll_to_y(objects.chatting_area_box, LV_COORD_MAX, LV_ANIM_OFF);

    // 5. Clear the keyboard input area
    lv_textarea_set_text(objects.textarea_1, "");
    lv_scr_load(objects.main);

    
}

void maintain_chat_limit() {
    // Set a threshold lower than your 3000 limit 
    // to leave plenty of room for the incoming message.
    const size_t THRESHOLD = 2000; 
    
    // Get the current text and its length
    const char *current_text = lv_textarea_get_text(objects.chatting_area_box);
    size_t current_len = strlen(current_text);

    if (current_len > THRESHOLD) {
        // We need to delete old messages. Let's drop roughly the first 500 characters.
        // strchr finds the next newline ('\n') AFTER the 500th character
        // so we don't chop a word or timestamp in half.
        const char *cut_point = strchr(current_text + 500, '\n');

        if (cut_point != NULL) {
            // Replace the text area with everything AFTER the cut point
            lv_textarea_set_text(objects.chatting_area_box, cut_point + 1);
        } else {
            // Failsafe: if no newline is found, clear it to prevent a crash
            lv_textarea_set_text(objects.chatting_area_box, "");
        }
    }
}

void update_rssi_ui(){
    char buf[16];
    sprintf(buf, "%d dB", last_rssi);

    lv_label_set_text(objects.rssi_text, buf);
}

void parse_lora_packet(String line){
    if(!line.startsWith("+RCV=")) return;

    int sender, length, rssi, snr;
    char payload[128];
    int parsed = sscanf(line.c_str(),
                        "+RCV=%d,%d,%[^,],%d,%d",
                        &sender,
                        &length,
                        payload,
                        &rssi,
                        &snr);
    if(parsed >= 3){
        String msg = String(payload);
        Serial.println("LoRa Packet Received:");
        Serial.println(msg);
        Serial.print("RSSI: ");
        Serial.println(rssi);
        process_lora_message(msg, rssi, sender);
        packet_counter++;
        update_packet_counter();
        last_rssi = rssi;
        update_rssi_ui();
    }
}

// ---------------- Loop ----------------
void loop(){
  static uint32_t last = 0;
  uint32_t now = millis();

  // lvgl tick
  if (now - last >= 5) {
    lv_tick_inc(5);
    last = now;
  }

  ui_tick();
  lv_timer_handler();

    while (LoRa.available()) {
        String line = LoRa.readStringUntil('\n');
        line.trim();

        if (line.length()) {
            Serial.println("RX: " + line);
            parse_lora_packet(line);
        }
    }

  delay(1);
}