#include <Arduino.h>
#include <lvgl.h>
#include <TFT_eSPI.h>
#include <Wire.h>
#include <RTClib.h>
#include "vars.h"
// ---------- IMPORTANT ----------
// DO NOT wrap EEZ headers with extern "C".
// EEZ generated headers use C++ features (templates, namespaces).
// Include them normally:
#include "ui.h"        // generated by EEZ Studio (ui.c / ui.h must be in project)
#include "screens.h"

RTC_DS3231 rtc;


// Calibration constants
const uint16_t RAW_MIN_X = 429;
const uint16_t RAW_MAX_X = 3593;
const uint16_t RAW_MIN_Y = 1905;
const uint16_t RAW_MAX_Y = 3345;

const bool SWAP_AXES = false;
const bool INVERT_X  = true;
const bool INVERT_Y  = false;

// ---------------- Display ----------------
TFT_eSPI tft = TFT_eSPI();
HardwareSerial LoRa(1);
static lv_disp_draw_buf_t draw_buf;
static lv_color_t buf1[320 * 40];

//LORA CODES
// ====== add / replace globals ======
int last_rssi = -127;
float last_snr = 0.0f;
unsigned long last_packet_time = 0;
unsigned long last_time_ui_update = 0;

int my_address = 3;
int target_address = 2;  // default
int my_network_id = 18;
int packet_counter = 0;



void loraAT(String cmd){
    while(LoRa.available()) LoRa.read();
    LoRa.print(cmd + "\r\n");  // not println
    delay(600);
    String r = "";
    while(LoRa.available()) r += (char)LoRa.read();
    r.trim();
    Serial.println(cmd + " => " + (r.length() ? r : "NO RESPONSE"));
}

// ====== top bar / main screen sync ======
void sync_topbar_ui() {
    char buf[32];

    snprintf(buf, sizeof(buf), " ID  : %d", my_network_id);
    lv_label_set_text(objects.net_id, buf);

    snprintf(buf, sizeof(buf), "AD  : %d", my_address);
    lv_label_set_text(objects.net_id_1, buf);

    snprintf(buf, sizeof(buf), "%d", target_address);
    lv_label_set_text(objects.obj5, buf);
}

void update_time_ui() {
    char buf[8];
    get_time_string(buf);
    lv_label_set_text(objects.time_display, buf);
}

void update_packet_counter() {
    char buf[16];
    snprintf(buf, sizeof(buf), "%d", packet_counter);
    lv_label_set_text(objects.packets_text, buf);
}

void update_last_received_ui() {
    char buf[32];

    if (last_packet_time == 0) {
        strcpy(buf, "<1 s ago");
    } else {
        unsigned long age_ms = millis() - last_packet_time;

        if (age_ms < 1000) {
            strcpy(buf, "<1 s ago");
        } else if (age_ms < 60000) {
            snprintf(buf, sizeof(buf), "%lu s ago", age_ms / 1000);
        } else {
            snprintf(buf, sizeof(buf), "%lu m ago", age_ms / 60000);
        }
    }

    lv_label_set_text(objects.last_received_text, buf);
}

void update_rssi_ui() {
    char buf[16];
    snprintf(buf, sizeof(buf), "%d dBm", last_rssi);
    lv_label_set_text(objects.rssi_text, buf);

    if (last_rssi > -90) {
        lv_label_set_text(objects.rssi_status, "GOOD");
        lv_obj_set_style_text_color(objects.rssi_status, lv_color_hex(0x42B897), 0);
    } else if (last_rssi > -105) {
        lv_label_set_text(objects.rssi_status, "OK");
        lv_obj_set_style_text_color(objects.rssi_status, lv_color_hex(0xD9A441), 0);
    } else {
        lv_label_set_text(objects.rssi_status, "WEAK");
        lv_obj_set_style_text_color(objects.rssi_status, lv_color_hex(0xFF0000), 0);
    }
}

void update_snr_ui() {
    char buf[16];
    snprintf(buf, sizeof(buf), "%.1f dB", last_snr);
    lv_label_set_text(objects.snr_text, buf);

    if (last_snr > 10.0f) {
        lv_label_set_text(objects.snr_status, "EXCELLENT");
        lv_obj_set_style_text_color(objects.snr_status, lv_color_hex(0x42B897), 0);
    } else if (last_snr > 5.0f) {
        lv_label_set_text(objects.snr_status, "GOOD");
        lv_obj_set_style_text_color(objects.snr_status, lv_color_hex(0x42B897), 0);
    } else if (last_snr > 0.0f) {
        lv_label_set_text(objects.snr_status, "OK");
        lv_obj_set_style_text_color(objects.snr_status, lv_color_hex(0xD9A441), 0);
    } else {
        lv_label_set_text(objects.snr_status, "WEAK");
        lv_obj_set_style_text_color(objects.snr_status, lv_color_hex(0xFF0000), 0);
    }
}




static inline int32_t fmap_clamped(int32_t val, int32_t in_min, int32_t in_max,
                                   int32_t out_min, int32_t out_max) {
    if (in_max == in_min) return out_min;

    long mapped = (long)(val - in_min) * (out_max - out_min) /
                  (long)(in_max - in_min) + out_min;

    if (mapped < out_min) return out_min;
    if (mapped > out_max) return out_max;
    return (int32_t)mapped;
}

// ---------------- Flush ----------------
void my_disp_flush(lv_disp_drv_t *disp,
                   const lv_area_t *area,
                   lv_color_t *color_p){
  uint32_t w = (uint32_t)(area->x2 - area->x1 + 1);
  uint32_t h = (uint32_t)(area->y2 - area->y1 + 1);

  tft.startWrite();
  tft.setAddrWindow(area->x1, area->y1, w, h);
  tft.pushColors((uint16_t *)color_p, w * h, false);
  tft.endWrite();

  lv_disp_flush_ready(disp);
}

void my_touch_read(lv_indev_drv_t *indev, lv_indev_data_t *data) {
    uint16_t tx = 0, ty = 0;
    bool pressed = tft.getTouch(&tx, &ty);

    const uint16_t sw = tft.width();   // 320
    const uint16_t sh = tft.height();  // 240

    if (!pressed) {
        data->state = LV_INDEV_STATE_REL;
        return;
    }

    data->state = LV_INDEV_STATE_PR;

    bool scaled = (tx <= sw && ty <= sh);

    int32_t mx, my;

    if (scaled) {
        mx = SWAP_AXES ? ty : tx;
        my = SWAP_AXES ? tx : ty;
    } else {
        if (SWAP_AXES) {
            mx = fmap_clamped(ty, RAW_MIN_Y, RAW_MAX_Y, 0, sw);
            my = fmap_clamped(tx, RAW_MIN_X, RAW_MAX_X, 0, sh);
        } else {
            mx = fmap_clamped(tx, RAW_MIN_X, RAW_MAX_X, 0, sw);
            my = fmap_clamped(ty, RAW_MIN_Y, RAW_MAX_Y, 0, sh);
        }
    }

    if (INVERT_X) mx = sw - mx;
    if (INVERT_Y) my = sh - my;

    if (mx < 0) mx = 0;
    if (mx > sw) mx = sw;
    if (my < 0) my = 0;
    if (my > sh) my = sh;

    data->point.x = (lv_coord_t)mx;
    data->point.y = (lv_coord_t)my;

    //Serial.printf("TOUCH RAW: %u %u | MAPPED: %ld %ld\n", tx, ty, mx, my);
}

void get_time_string(char *buf){
    DateTime now = rtc.now();
    sprintf(buf,"%02d:%02d", now.hour(), now.minute());
}

void parse_lora_packet(String line) {
    if (!line.startsWith("+RCV=")) return;

    int sender, length;
    int rssi, snr;
    char payload[128];

    // Step 1: extract sender + length
    int first = line.indexOf(',');
    int second = line.indexOf(',', first + 1);

    if(first == -1 || second == -1) return;

    sender = line.substring(5, first).toInt();
    length = line.substring(first + 1, second).toInt();

    // Step 2: find LAST two commas (RSSI, SNR)
    int last_comma = line.lastIndexOf(',');
    int second_last = line.lastIndexOf(',', last_comma - 1);

    if(last_comma == -1 || second_last == -1) return;

    // Step 3: extract payload safely
    String payload_str = line.substring(second + 1, second_last);
    payload_str.toCharArray(payload, sizeof(payload));

    // Step 4: extract RSSI + SNR
    rssi = line.substring(second_last + 1, last_comma).toInt();
    snr  = line.substring(last_comma + 1).toInt();

    // Debug
    Serial.println("Parsed OK:");
    Serial.println(payload);
    Serial.print("RSSI: "); Serial.println(rssi);
    Serial.print("SNR: "); Serial.println(snr);

    // Update UI
    last_rssi = rssi;
    last_snr = snr;
    last_packet_time = millis();

    packet_counter++;

    update_packet_counter();
    update_rssi_ui();
    update_snr_ui();
    update_last_received_ui();
}



// ---------------- Setup ----------------
void setup(){
  Serial.begin(115200);
  delay(100);
    // RYLR998 UART — add this before AT commands
  LoRa.begin(9600, SERIAL_8N1, 14, 13);  // RX=13, TX=14
  delay(300);

    Serial.println("=== LORA INIT ===");
    loraAT("AT");
    loraAT("AT+BAND=865000000");
    loraAT("AT+PARAMETER=11,7,1,12");
    loraAT("AT+CRFOP=14");                 // TX power 14dBm
    loraAT("AT+ADDRESS=" + String(my_address));

    Serial.println("=== VERIFY ===");
    loraAT("AT+BAND?");
    loraAT("AT+PARAMETER?");
    loraAT("AT+ADDRESS?");
    Serial.println("=== LORA DONE ===");

    delay(200);
    while(LoRa.available()){
    Serial.write(LoRa.read());  // should print "+OK" in Serial Monitor
    }
    delay(100);

    Wire.begin(25, 26);   // your RTC pins

    if (!rtc.begin()) {
        Serial.println("RTC not found");
    }

    tft.begin();
    tft.setRotation(3);


  lv_init();


  // Display driver
  lv_disp_draw_buf_init(&draw_buf, buf1, NULL, 320 * 40);

  static lv_disp_drv_t disp_drv;
  lv_disp_drv_init(&disp_drv);
  disp_drv.flush_cb = my_disp_flush;
  disp_drv.draw_buf = &draw_buf;
  disp_drv.hor_res = 320;
  disp_drv.ver_res = 240;
  lv_disp_drv_register(&disp_drv);

  // Touch driver (pointer)
  static lv_indev_drv_t indev_drv;
  lv_indev_drv_init(&indev_drv);
  indev_drv.type = LV_INDEV_TYPE_POINTER;
  indev_drv.read_cb = my_touch_read;
  lv_indev_drv_register(&indev_drv);

  // ----- EEZ: initialize UI + Flow (ui_init is generated by EEZ) -----
  // Make sure ui.c/.cpp and the rest of the EEZ-generated files are present in the sketch.
  ui_init();
lv_scr_load(objects.main);
// In setup() after ui_init() — keeps scroll, disables cursor tap

    LoRa.printf("AT+ADDRESS=%d\r\n", my_address);
    delay(300);



  Serial.println("ui_init() done");

    
// ====== in setup(), after ui_init() and lv_scr_load(objects.main); ======
sync_topbar_ui();
update_time_ui();
update_packet_counter();
update_last_received_ui();
update_rssi_ui();
update_snr_ui();
}



// ---------------- Loop ----------------
void loop(){
  static uint32_t last = 0;
  uint32_t now = millis();

  // lvgl tick
  if (now - last >= 5) {
    lv_tick_inc(5);
    last = now;
  }

  ui_tick();
  lv_timer_handler();

while (LoRa.available()) {
    String line = LoRa.readStringUntil('\n');
    line.trim();

    if (line.length()) {
        Serial.println("RX: " + line);
        parse_lora_packet(line);
    }
}
if (millis() - last_time_ui_update >= 1000) {
    update_time_ui();
    update_last_received_ui();
    last_time_ui_update = millis();
}

  delay(1);
}